### ISSUE TITLE
Fix name

### ISSUE THREAD

**Issue by archer884** [vmchale/project-init#3]
This is a small bug, and maybe you'll just want to close it, but the name is all wrong. It's clear to me this project should have been named "Magnum P.I."

![image](https://user-images.githubusercontent.com/679494/27656101-676852a4-5c0d-11e7-8b9e-1ef57857cb82.png)

Then again, maybe I can think of some project that would use that name... >.>

**Comment by vmchale** [comment]
If I manage to work that into the Readme I'll let you know :)
